list = ["Cereal", "Hamburger", "Pizza", "Salad", "Cheese"]
print(list)
list.append("Cake")
print(list)
list.sort()
print(list)
list.insert(3, "Chicken")
print(list)
list.pop(6)
print(list)
list.sort(reverse=True)
print(list)
len(list)
print(len(list))
list.clear()
print(list)