friends = []
f1 = input("Who do you want to invite? ")
f2 = input("Who do you want to invite? ")
f3 = input("Who do you want to invite? ")
f4 = input("Who do you want to invite? ")
friends.append(f1)
friends.append(f2)
friends.append(f3)
friends.append(f4)
print(friends)
f5 = input("Who s unable to come? ")
friends.remove(f5)
print(friends)
friends.remove(input("Who do you want to remove? "))
print(friends)
f6 = input("Who is unable to come now?")
n=friends.index(f6)
friends.pop(n)
print(friends)
print(friends.pop(friends.index(input("Who is unable to come now? "))))
